project_name: panel
builds:
  -
    id: panel
    binary: panel
    env:
      - CGO_ENABLED=0
    goos:
      - linux
    goarch:
      - amd64
      - arm64
    goamd64:
      - v2
    ldflags:
      - -s -w --extldflags "-static -fpic"
archives:
  -
    id: panel-archive
    builds:
      - panel
    format: zip
    wrap_in_directory: false
    strip_parent_binary_folder: true
    rlcp: true
    files:
      - LICENSE
      - public/*
      - storage/*
      - database/*
      - scripts/*
      - panel-example.conf
