name: Welcome
on:
  pull_request:
    types: [ opened, closed ]
  issues:
    types: [ opened ]
jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: wow-actions/welcome@v1
        with:
          FIRST_ISSUE: |
            Hi @{{ author }} 👋

            Thanks for opening this issue to HaoZi Panel, we will respond as soon as possible! 💖
            感谢您向 耗子面板 提出此 Issue，我们将尽快反馈！ 💖

          FIRST_PR: |
            Hi @{{ author }} 👋

            Thanks for opening this PR to HaoZi Panel, But we use JiHu GitLab to develop, please submit PR to our JiHu GitLab repository, thank you! 💖
            感谢您向 耗子面板 提交此 PR，但是我们使用 极狐GitLab 进行开发，请提交 PR 到我们的 极狐GitLab 仓库，谢谢！ 💖

          STAR_MESSAGE: |
            If you like this project, please ⭐star⭐ our repository to support us!
            如果您喜欢这个项目，请 Star 仓库给予我们支持！
